name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
    - name: Initialize Terraform
      run: terraform init
    - name: Terraform Plan
      run: terraform plan
    - name: Apply Terraform
      run: terraform apply -auto-approve
  

  build:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    - name: Build Docker image
      run: docker build -t hello-world-app:latest .
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Docker image
      run: |
        docker tag hello-world-app:latest <container-registry>/hello-world-app:latest
        docker push <container-registry>/hello-world-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Configure kubectl
      run: |
        aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name $(terraform output -raw cluster_name)
    - name: Create namespace if not exists
      run: kubectl create namespace my-namespace || true
    - name: Deploy with Helm
      env:
        VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
        VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
      run: |
        helm install hello-world-app ./helm-chart --namespace my-namespace
