name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  terraform:
    runs-on: ubuntu-latest

    env: 
      AWS_REGION: 'us-east-1'

    outputs:
      eks_cluster_name: ${{ steps.terraform.outputs.eks_cluster_name }}


    steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v2

     - name: Initialize Terraform
       working-directory: ./terraform
       run: terraform init
       env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

     - name: Plan Terraform
       working-directory: ./terraform
       run: terraform plan
       env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ env.AWS_REGION }}

     - name: Apply Terraform
       working-directory: ./terraform
       run: terraform apply -auto-approve
       env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ env.AWS_REGION }}


  build:
    runs-on: ubuntu-latest
    needs: terraform

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t hello-world-app:latest ./docker

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Docker Image
      run: |
        docker tag hello-world-app:latest ${{ secrets.DOCKER_USERNAME }}/hello-world-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/hello-world-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-east-1


      - name: Set up kubectl
        run: |
          aws eks --region us-east-1 update-kubeconfig --name mayank-eks-4

      - name: Set up Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash


      - name: Deploy to Kubernetes with Helm
        run: |
          helm upgrade --install hello-world ./k8s/hello-world-chart \
            --namespace custom-namespace \
            --set image.repository=${{ secrets.DOCKER_USERNAME }}/hello-world-app \
            --set image.tag=latest
