name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  terraform:
    runs-on: ubuntu-latest

    env: 
      AWS_REGION: 'us-east-1'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Initialize Terraform
      working-directory: ./terraform
      run: terraform init
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Plan Terraform
      working-directory: ./terraform
      run: terraform plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Apply Terraform
      working-directory: ./terraform
      run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

  build:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    - name: Build Docker image
      run: docker build -t hello-world-app:latest .
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Docker image
      run: |
        docker tag hello-world-app:latest mak53/hello-world-app:latest
        docker push mak53/hello-world-app:latest

  deploy:
  runs-on: ubuntu-latest
  env: 
    AWS_REGION: 'us-east-1'

  needs: build
  
  steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Configure AWS CLI
    uses: aws-actions/configure-aws-credentials@v1
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ env.AWS_REGION }}

  - name: Configure kubectl
    run: |
      aws eks --region ${{ env.AWS_REGION }} update-kubeconfig --name $(terraform output -raw cluster_name)

  - name: Create namespace if not exists
    run: |
      kubectl get namespace my-namespace || kubectl create namespace my-namespace

  - name: Deploy with Helm
    env:
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
    run: |
      helm upgrade --install hello-world-app ./helm-chart --namespace my-namespace

